[Server]
port=8182

[Rename]
code="rename"
input_size=2048
output_size=8
path_to_model='rename_trained'
diversity_penalty=5.0
temperature=1.1
length_penalty=1
beam_size=10

[Comment]
code="comment"
input_size=2048
output_size=512
path_to_comment_model='comment_generation_special_trained/'
path_to_docstring_model='comment_generation_trained'
top_k=40
top_p=1
temperature=1
length_penalty=100
beam_size=5

[ErrorCorrection]
code="error"
enabled=false
input_size=2048
output_size=2048
path_to_model='wizard_trained'
top_k=50
top_p=1
temperature=1
length_penalty=1
